processors:
  resource:
    attributes:
    - key: cloud.zone
      value: "zone-1"
      action: upsert
    - key: host.name
      value: "sample-container"
      action: upsert
    - key: appdynamics.application
      action: upsert
      value: "ticket-hub"

receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      process:
        include:
          match_type: "docker*"

exporters:
  appdynamics:
    metrics:
      http:
        endpoint: mock-cms:5000
    account: customer1
    access_key: key


service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resource]
      exporters: [appdynamics]