# AD-Capital Approval Node
#
# The current image (appddemo/adcapital-tomcat:latest) of the Approval Node contains
# performance and security issues that have been resolved in the version V2 image lincharles/adcapital-tomcat:latest
# The V2 image appears to not have been instrumented with AppDynamics
#
# Update History
# V1 - appddemo/adcapital-tomcat:latest
# V2 - lincharles/adcapital-tomcat:latest
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval
  labels:
    app: approval
    name: approval
    keel.sh/policy: force
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approval
  strategy:
    type: Recreate
  template:
    metadata:
      name: approval
      labels:
        app: approval
    spec:
      containers:
        - name: approval
          image: lincharles/adcapital-tomcat:latest
          imagePullPolicy: Always
          #image: appddemo/adcapital-tomcat:latest
          env:
            - name: ROLE
              value: approval
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /hostroot
              name: hostroot
              readOnly: true
            - mountPath: /project
              name: project
      restartPolicy: Always
      volumes:
        - name: hostroot
          hostPath:
            path: /
            type: Directory
        - name: project
      initContainers:
        - image: appddemo/adcapital-project
          name: provider
          volumeMounts:
            - mountPath: /project
              name: project
status: {}
# Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: approval
  name: approval
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: approval
status:
  loadBalancer: {}
