version: '3'
services:
  api:
    image: ${DTR_SAMPLE_APP_REPO}/py-apigateway:${TAG}
    ports:
      - "5001:5000"
    container_name: py-api-gateway
    entrypoint: ["opentelemetry-instrument",  "python", "app.py","--exporter", "otc"]
    env_file:
      - setup.env
    logging:
      driver: none

  bookings:
    image: ${DTR_SAMPLE_APP_REPO}/node-bookings:${TAG}
    container_name: node-bookings
    entrypoint: ["node", "index.js"]
    env_file:
      - setup.env
    logging:
      driver: none

  payments:
    image: dtr.corp.appdynamics.com/rhynier.myburgh/dotnet-payments
    container_name: dotnet-payments
    entrypoint: ["dotnet",  "PaymentService.dll", "--exporter", "otc"]
    env_file:
      - setup.env
    logging:
      driver: none

  # payments:
  #   image: ${DTR_SAMPLE_APP_REPO}/py-payments:${TAG}
  #   container_name: py-payments
  #   entrypoint: ["opentelemetry-instrument",  "python", "app.py" ,"--exporter", "otc"]
  #   env_file:
  #     - setup.env
  #   logging:
  #     driver: none

  reservations:
    image: ${DTR_SAMPLE_APP_REPO}/py-reservations:${TAG}
    container_name: py-reservations
    entrypoint: ["opentelemetry-instrument",  "python", "app.py", "--exporter", "otc"]
    env_file:
      - setup.env
    logging:
      driver: none

  # Collector
  otel-collector:
    image: ${DTR_OT_REPO}/otelcontribcol:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-config.yml:/etc/otel-config.yml
    ports:
      - 55678:55678       # receiving port
      - 55680
    depends_on:
      - otismockinjestservice
      #- mock-traces-ingest
    env_file:
      - setup.env
    logging:
      driver: none

  #mock-traces-ingest:
  #  image: ${DTR_SAMPLE_APP_REPO}/mock-traces-ingest:${TAG}
  #  container_name: mock-traces-ingest
  #  entrypoint: ["./server"]
  #  env_file:
  #    - setup.env

  otismockinjestservice:
    image: dtr.corp.appdynamics.com/rhynier.myburgh/otismockinjestservice:${TAG}
    container_name: otis-mock-injest
    env_file:
      - setup.env

  # Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

